groups:
  - name: pizzaai
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Alta tasa de errores HTTP"
          description: "La tasa de errores HTTP 5xx es mayor al 10%"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta latencia HTTP"
          description: "El 95% de las peticiones HTTP tardan más de 1 segundo"

      - alert: RedisConnectionError
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Error de conexión a Redis"
          description: "No se puede conectar al servidor Redis"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de memoria"
          description: "El uso de memoria física es mayor al 80%" 