name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run linting
        run: |
          # Ejecutar flake8 solo para errores críticos
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          # Verificar formato con black
          black . --check || true

      - name: Run tests
        run: |
          pytest tests/ -v || echo "No tests found" 