name: Repository Setup - Part 2
on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create More Issues
        uses: actions/github-script@v5
        env:
          GH_PAT: ${{ secrets.GH_TOKEN }}
        with:
          script: |
            async function getMilestoneId(title) {
              const milestones = await github.rest.issues.listMilestones({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
              });
              
              const milestone = milestones.data.find(m => m.title.includes(title));
              return milestone ? milestone.number : null;
            }

            const sprint1Id = await getMilestoneId('Sprint 1');
            const sprint2Id = await getMilestoneId('Sprint 2');
            const sprint3Id = await getMilestoneId('Sprint 3');

            const issues = [
              {
                title: '📊 Setup de Monitoreo y Logging',
                body: '## Descripción\nConfigurar el sistema de monitoreo y logging para la aplicación.\n\n## Tareas\n- [ ] Implementar logging estructurado\n- [ ] Configurar métricas de aplicación\n- [ ] Implementar trazabilidad distribuida\n- [ ] Configurar dashboards de monitoreo\n\n## Criterios de Aceptación\n- Sistema de logging implementado y funcionando\n- Métricas siendo recolectadas\n- Dashboards configurados y mostrando datos',
                milestone: sprint1Id,
                labels: ['monitoring', 'infrastructure']
              },
              {
                title: '🗄️ Diseño e Implementación del Modelo de Datos',
                body: `## Objetivo\nDiseñar e implementar el modelo de datos para el sistema de recomendación.\n\n## Tareas\n### Diseño del Esquema\n- [ ] Modelos de usuario\n- [ ] Modelos de recetas\n- [ ] Modelos de ingredientes\n\n### Sistema de Persistencia\n- [ ] Configuración de PostgreSQL\n- [ ] Migraciones\n- [ ] Índices y optimizaciones`,
                milestone: sprint2Id,
                labels: ['backend', 'high-priority']
              },
              {
                title: '🔌 Desarrollo de API Core',
                body: `## Objetivo\nImplementar la API REST para el sistema.\n\n## Tareas\n### Endpoints Básicos\n- [ ] CRUD de usuarios\n- [ ] CRUD de recetas\n- [ ] CRUD de ingredientes\n\n### Sistema de Autenticación\n- [ ] JWT implementation\n- [ ] Roles y permisos\n- [ ] Rate limiting\n\n### Documentación API\n- [ ] OpenAPI/Swagger\n- [ ] Postman collection\n- [ ] Ejemplos de uso`,
                milestone: sprint2Id,
                labels: ['backend', 'high-priority']
              },
              {
                title: '🧮 Implementación del Motor de Recomendación',
                body: `## Objetivo\nDesarrollar el sistema de recomendación de recetas.\n\n## Tareas\n### Integración USDA\n- [ ] Cliente API\n- [ ] Caché de datos\n- [ ] Sincronización\n\n### Algoritmo de Recomendación\n- [ ] Lógica base\n- [ ] Filtros y ordenamiento\n- [ ] Personalización\n\n### Sistema de Caché\n- [ ] Configuración Redis\n- [ ] Estrategias de caché\n- [ ] Invalidación`,
                milestone: sprint2Id,
                labels: ['backend', 'high-priority']
              },
              {
                title: '🎨 Desarrollo del Dashboard',
                body: `## Objetivo\nCrear una interfaz de usuario moderna y funcional.\n\n## Tareas\n### Diseño UI/UX\n- [ ] Wireframes\n- [ ] Componentes base\n- [ ] Tema y estilos\n\n### Implementación Frontend\n- [ ] Setup React\n- [ ] Routing\n- [ ] Estado global\n\n### Integración API\n- [ ] Cliente HTTP\n- [ ] Manejo de errores\n- [ ] Loading states`,
                milestone: sprint3Id,
                labels: ['frontend', 'high-priority']
              },
              {
                title: '📈 Implementación del Sistema de Monitoreo en Producción',
                body: `## Objetivo\nImplementar un sistema completo de monitoreo para producción.\n\n## Tareas\n### Métricas de Negocio\n- [ ] KPIs\n- [ ] Reportes\n- [ ] Analytics\n\n### Sistema de Alertas\n- [ ] Configuración\n- [ ] Notificaciones\n- [ ] Escalamiento\n\n### Dashboard Operacional\n- [ ] Métricas en tiempo real\n- [ ] Logs centralizados\n- [ ] Estado del sistema`,
                milestone: sprint3Id,
                labels: ['monitoring', 'medium-priority']
              }
            ];

            for (const issue of issues) {
              try {
                await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: issue.title,
                  body: issue.body,
                  milestone: issue.milestone,
                  labels: issue.labels
                });
                console.log(`Created issue: ${issue.title}`);
              } catch (error) {
                console.error(`Error creating issue ${issue.title}: ${error}`);
              }
            } 