name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {}  # Sin permisos especiales
    steps:
      - uses: actions/checkout@v2  # Versión estable y ampliamente usada
      
      - name: Set up Python
        uses: actions/setup-python@v2  # Versión estable y ampliamente usada
        with:
          python-version: '3.9'
      
      - name: Test Python
        run: |
          python --version
          python -c "print('Hello from GitHub Actions!')" 