name: Python application

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5  # v1.2.0
    - uses: actions/setup-python@41b7212b1668f5de9d65e9c82aa777e6bbedb3a8  # v1.2.0
      with:
        python-version: '3.9'
    - run: python -V 