name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 black isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run linting
        continue-on-error: true  # Permitir que falle el linting inicialmente
        run: |
          # Ejecutar flake8 solo para errores críticos
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Ejecutar black en modo check
          black . --check --diff
          # Ejecutar isort en modo check
          isort . --check-only --diff
      
      - name: Run tests
        run: |
          python -m pytest tests/ -v
      
      - name: Run tests with coverage
        if: success()  # Solo si los tests básicos pasan
        run: |
          pytest --cov=./ --cov-report=xml
          
      - name: Upload coverage report
        if: success()  # Solo si todo lo anterior pasa
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: false  # No fallar si hay problemas con Codecov 