name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v2.5.0
      
      - name: Set up Python
        uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # v2.3.0
        with:
          python-version: '3.9'
      
      - name: Test Python
        run: |
          python --version
          python -c "print('Hello from GitHub Actions!')" 