name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      
      - name: Test Python
        run: python --version 